### ISSUE TITLE
Minor: unnecessary synchronization in Driver

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jdbc#46]
I think the synchronization isn't necessary, it's called only from the static initializer and the JVM guarantees that it's not concurrent and that's its called only once, so we also don't need the `registered` field.

https://github.com/hazelcast/hazelcast-jdbc/blob/0e5037d47c19448c3202c897db981c689d91e4b6/src/main/java/com/hazelcast/jdbc/Driver.java#L86-L95

See mysql driver: https://github.com/mysql/mysql-connector-j/blob/18bbd5e68195d0da083cbd5bd0d05d76320df7cd/src/main/user-impl/java/com/mysql/cj/jdbc/Driver.java#L53-L59

**Comment by JackPGreen** [comment]
Fixed in 576f8d7a18ef940405eae7f8a42d264e8b1209de
